---
title: China 2019 Journal
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: false
  steps:
    title: Steps
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: steps
  values:
    title: 
    date: 2019-07-01 00:00:00 -0700
markdown: kramdown
highlighter: rouge
lsi: false
description: China 2019 Journal
baseurl: "/china-2019"
url: http://stephenlange.org
color: "#f2f2f2"
